FROM python:3.14-slim

WORKDIR /app

COPY pyproject.toml uv.lock README.md ./
COPY src ./src

RUN pip install uv
RUN uv sync --locked

CMD ["uv", "run", "uvicorn", "todo_app.services:app", "--host", "0.0.0.0", "--port", "8000"]