[project]
name = "todo-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eyad Jawad" }
]
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.22.1",
    "argon2-cffi>=25.1.0",
    "fastapi[standard]>=0.141.1",
    "readchar>=4.2.2",
    "rich>=15.0.0",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
todo-app = "todo_app.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.5",
]

[tool.pytest.ini_options]
testpaths = ["src/tests"]
addopts = "--cov=."

[tool.coverage.run]
source = ["."]
omit = ["src/tests/*"]

[tool.ruff]
line-length = 80

[tool.black]
line-length = 80
target-version = ["py311"]

[tool.mypy]
python_version = "3.11"
