name: Test Todo App

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: todo
          POSTGRES_USER: todo
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U todo -d todo"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install justfile
        run: sudo apt install just

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --locked

      - name: Run tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: todo
          POSTGRES_USER: todo
          POSTGRES_PASSWORD: test_password
          REDIS_HOST: localhost
        run: just all
